name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 8.11.1 --distribution-type all

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

      # If you have other reports or artifacts to upload, add another step.
      - name: Upload Problems Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: problems-report
          path: build/reports/problems/problems-report.html
