name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up a Java Development Kit (using Temurin/OpenJDK 11 – adjust version if needed)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3. Set up the Android SDK and install API level 33 (Android 13)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33

      # 4. (Optional) Cache Gradle dependencies to speed up builds
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # 5. Build the app using Gradle (adjust the gradle task if you need a different build variant)
      - name: Build Debug APK
        run: ./gradlew assembleDebug
